file_new = open(r'/Users/greek/PycharmProjects/exercises/old-exams/cakepoints/input.txt', 'r+')
file_diff = open(r'/Users/greek/PycharmProjects/exercises/old-exams/cakepoints/output.txt', 'a')
file_diff.truncate(0)
for line in file_new:
    name = line.split(':')
    splnr = line.split('/')
    splnr = splnr[0].split(':') + splnr[1].split(' ')
    oldPlus = int(splnr[2])
    oldMin = int(splnr[1])
    plus = str(line.count('+')+oldPlus)
    min = str(line.count('-')+oldMin)
    file_diff.write(name[0]+':'+min+'/'+plus+'\n')
file_new.close()
file_diff.close()
